# Generated by Django 3.2.3 on 2022-01-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
    ]
